name: Deploy

on:
  push:
    branches:
      - master

jobs:
  install-deps:
    if: github.repository == 'mazipan/login-page-css'
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install locked dependencies
        run: yarn install

      - name: Cache dependencies
        uses: actions/cache@v1
        id: cache-deps
        with:
          path: '.'
          key: ${{ github.sha }}

  deploy_gh_pages:
    if: github.repository == 'mazipan/login-page-css'
    name: Deploy
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Restore cached dependencies
        uses: actions/cache@v1
        id: restore-deps
        with:
          path: '.'
          key: ${{ github.sha }}

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Build UI
        run: yarn build

      - name: GitHub Pages Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./dist
